package com.example.bulkyo.navigation

sealed class Screen(val route: String) {
    object Splash : Screen("splash")
    object AppIntroduction : Screen("app_introduction")
    object Onboarding1 : Screen("onboarding1")
    object Onboarding2 : Screen("onboarding2")
    object Onboarding3 : Screen("onboarding3")
    object SignUp : Screen("signup")
    object Login : Screen("login")
    object ForgotPassword : Screen("forgot_password")
    object OtpVerification : Screen("otp_verification")
    object CreateProfile : Screen("create_profile")
    object HomeDashboard : Screen("home_dashboard")
    object Search : Screen("search")
    object Categories : Screen("categories")
    object CategoryDetails : Screen("category_details/{categoryId}") {
        fun createRoute(categoryId: String) = "category_details/$categoryId"
    }
    object Notifications : Screen("notifications")
    object Messages : Screen("messages")
    object ChatList : Screen("chat_list")
    object IndividualChat : Screen("individual_chat/{chatId}") {
        fun createRoute(chatId: String) = "individual_chat/$chatId"
    }
    object VoiceCall : Screen("voice_call")
    object VideoCall : Screen("video_call")
    object UserProfile : Screen("user_profile")
    object EditProfile : Screen("edit_profile")
    object Settings : Screen("settings")
    object PrivacySettings : Screen("privacy_settings")
    object SecuritySettings : Screen("security_settings")
    object ChangePassword : Screen("change_password")
    object HelpCenter : Screen("help_center")
    object FAQ : Screen("faq")
    object ContactSupport : Screen("contact_support")
    object FeedbackForm : Screen("feedback_form")
    object Favorites : Screen("favorites")
    object RecentActivity : Screen("recent_activity")
    object ItemDetails : Screen("item_details/{itemId}") {
        fun createRoute(itemId: String) = "item_details/$itemId"
    }
    object Reviews : Screen("reviews")
    object AddReview : Screen("add_review")
    object Wishlist : Screen("wishlist")
    object Cart : Screen("cart")
    object Checkout : Screen("checkout")
    object AddressManagement : Screen("address_management")
    object PaymentMethods : Screen("payment_methods")
    object PaymentSuccess : Screen("payment_success")
    object OrderSummary : Screen("order_summary")
    object OrderTracking : Screen("order_tracking")
    object OrderHistory : Screen("order_history")
    object Coupons : Screen("coupons")
    object SubscriptionPlans : Screen("subscription_plans")
    object MembershipDashboard : Screen("membership_dashboard")
    object AnalyticsOverview : Screen("analytics_overview")
    object Reports : Screen("reports")
    object Calendar : Screen("calendar")
    object ScheduleManagement : Screen("schedule_management")
    object BookingScreen : Screen("booking_screen")
    object BookingConfirmation : Screen("booking_confirmation")
    object LocationMap : Screen("location_map")
    object GPSTracking : Screen("gps_tracking")
    object FileUpload : Screen("file_upload")
    object DocumentViewer : Screen("document_viewer")
    object MediaGallery : Screen("media_gallery")
    object CameraIntegration : Screen("camera_integration")
    object QRScanner : Screen("qr_scanner")
    object AIAssistant : Screen("ai_assistant")
    object VoiceAssistant : Screen("voice_assistant")
    object CommunityFeed : Screen("community_feed")
    object PostCreation : Screen("post_creation")
    object Leaderboard : Screen("leaderboard")
    object Achievements : Screen("achievements")
    object ReferralProgram : Screen("referral_program")
    object AdminDashboard : Screen("admin_dashboard")
    object LogoutConfirmation : Screen("logout_confirmation")
    object SuccessThankYou : Screen("success_thank_you")
}
